"use client";

import { useState } from "react";

interface ReportSection {
  id: string;
  number: number;
  title: string;
  content: string;
  expanded: boolean;
  sources?: string[];
}

interface ResearchReportProps {
  sections: ReportSection[];
  onSectionClick: (sectionId: string) => void;
  onUpdateSection: (sectionId: string, content: string) => void;
}

export default function ResearchReport({
  sections,
  onSectionClick,
  onUpdateSection,
}: ResearchReportProps) {
  const [expandedSections, setExpandedSections] = useState<Set<string>>(
    new Set(sections.map((s) => s.id))
  );

  const toggleSection = (sectionId: string) => {
    const newExpanded = new Set(expandedSections);
    if (newExpanded.has(sectionId)) {
      newExpanded.delete(sectionId);
    } else {
      newExpanded.add(sectionId);
    }
    setExpandedSections(newExpanded);
  };

  return (
    <div className="max-w-5xl mx-auto p-6 space-y-4">
      {/* Report Header */}
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-white mb-2">
          Market Research Report
        </h1>
        <p className="text-gray-400 text-sm">
          Generated by MATRIX • {new Date().toLocaleDateString()}
        </p>
      </div>

      {/* Report Sections */}
      {sections.map((section) => {
        const isExpanded = expandedSections.has(section.id);

        return (
          <div
            key={section.id}
            className="bg-gray-800 border border-gray-700 rounded-lg overflow-hidden transition-all hover:border-gray-600"
          >
            {/* Section Header */}
            <button
              onClick={() => {
                toggleSection(section.id);
                onSectionClick(section.id);
              }}
              className="w-full flex items-center justify-between p-4 text-left hover:bg-gray-750 transition-colors"
            >
              <div className="flex items-center space-x-4 flex-1">
                <div className="flex items-center justify-center w-8 h-8 rounded-full bg-primary-600 text-white font-bold text-sm">
                  {section.number}
                </div>
                <h2 className="text-xl font-semibold text-white">
                  {section.title}
                </h2>
              </div>
              <div className="flex items-center space-x-3">
                {section.sources && section.sources.length > 0 && (
                  <span className="text-xs text-gray-400 bg-gray-900 px-2 py-1 rounded">
                    {section.sources.length} sources
                  </span>
                )}
                <svg
                  className={`w-5 h-5 text-gray-400 transition-transform ${
                    isExpanded ? "rotate-180" : ""
                  }`}
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M19 9l-7 7-7-7"
                  />
                </svg>
              </div>
            </button>

            {/* Section Content */}
            {isExpanded && (
              <div className="p-6 border-t border-gray-700 bg-gray-850">
                <div className="prose prose-invert max-w-none">
                  <div className="text-gray-300 leading-relaxed whitespace-pre-wrap">
                    {section.content || (
                      <div className="flex items-center space-x-2 text-gray-500 italic">
                        <svg
                          className="w-4 h-4 animate-spin"
                          fill="none"
                          viewBox="0 0 24 24"
                        >
                          <circle
                            className="opacity-25"
                            cx="12"
                            cy="12"
                            r="10"
                            stroke="currentColor"
                            strokeWidth="4"
                          ></circle>
                          <path
                            className="opacity-75"
                            fill="currentColor"
                            d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                          ></path>
                        </svg>
                        <span>Generating content...</span>
                      </div>
                    )}
                  </div>
                </div>

                {/* Data Sources */}
                {section.sources && section.sources.length > 0 && (
                  <div className="mt-6 pt-4 border-t border-gray-700">
                    <h4 className="text-sm font-semibold text-gray-400 mb-2">
                      Data Sources:
                    </h4>
                    <div className="flex flex-wrap gap-2">
                      {section.sources.map((source, idx) => (
                        <span
                          key={idx}
                          className="text-xs bg-gray-900 text-accent-400 px-2 py-1 rounded"
                        >
                          {source}
                        </span>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            )}
          </div>
        );
      })}
    </div>
  );
}

