"use client";

import { useState } from "react";

interface DataSource {
  name: string;
  url: string;
}

interface ReportSection {
  id: string;
  number: number;
  title: string;
  content: string;
  expanded: boolean;
  sources?: DataSource[];
}

interface ResearchReportProps {
  sections: ReportSection[];
  onSectionClick: (sectionId: string) => void;
  onUpdateSection: (sectionId: string, content: string) => void;
  onExpandedChange?: (expandedSections: Set<string>) => void;
  liveStatus?: string; // Live generation status
  isGenerating?: boolean; // Whether report is still generating
}

export default function ResearchReport({
  sections,
  onSectionClick,
  onUpdateSection,
  onExpandedChange,
  liveStatus,
  isGenerating = false,
}: ResearchReportProps) {
  // Start with all sections collapsed
  const [expandedSections, setExpandedSections] = useState<Set<string>>(
    new Set()
  );

  const toggleSection = (sectionId: string) => {
    const newExpanded = new Set(expandedSections);
    if (newExpanded.has(sectionId)) {
      newExpanded.delete(sectionId);
    } else {
      newExpanded.add(sectionId);
    }
    setExpandedSections(newExpanded);
    onExpandedChange?.(newExpanded);
  };

  const collapseAll = () => {
    setExpandedSections(new Set());
    onExpandedChange?.(new Set());
  };

  const expandAll = () => {
    const allIds = new Set(sections.map(s => s.id));
    setExpandedSections(allIds);
    onExpandedChange?.(allIds);
  };

  return (
    <div className="max-w-5xl mx-auto p-6 space-y-4">
      {/* Report Header */}
      <div className="mb-8 flex items-center justify-between">
        <div className="flex-1">
          <div className="flex items-center gap-4">
            <h1 className="text-3xl font-bold text-white">
              Market Research Report
            </h1>
            {isGenerating && liveStatus && (
              <div className="flex items-center gap-2">
                <div className="animate-pulse flex space-x-1">
                  <div className="w-2 h-2 bg-blue-500 rounded-full"></div>
                  <div className="w-2 h-2 bg-blue-500 rounded-full"></div>
                  <div className="w-2 h-2 bg-blue-500 rounded-full"></div>
                </div>
                <span className="text-blue-400 font-bold text-sm animate-pulse">
                  {liveStatus}
                </span>
              </div>
            )}
          </div>
          <p className="text-gray-400 text-sm mt-2">
            Generated by MATRIX • {new Date().toLocaleDateString()}
          </p>
        </div>
        <div className="flex space-x-2">
          <button
            onClick={expandAll}
            className="px-4 py-2 bg-gray-700 hover:bg-gray-600 text-white text-sm font-medium rounded-md transition-colors"
          >
            Expand All
          </button>
          <button
            onClick={collapseAll}
            className="px-4 py-2 bg-gray-700 hover:bg-gray-600 text-white text-sm font-medium rounded-md transition-colors"
          >
            Collapse All
          </button>
        </div>
      </div>

      {/* Report Sections */}
      {sections.map((section) => {
        const isExpanded = expandedSections.has(section.id);

        return (
          <div
            key={section.id}
            className="bg-gray-800 border border-gray-700 rounded-lg overflow-hidden transition-all hover:border-gray-600"
          >
            {/* Section Header */}
            <button
              onClick={() => {
                toggleSection(section.id);
                onSectionClick(section.id);
              }}
              className="w-full flex items-center justify-between p-4 text-left hover:bg-gray-750 transition-colors"
            >
              <div className="flex items-center space-x-4 flex-1">
                <div className="flex items-center justify-center w-8 h-8 rounded-full bg-primary-600 text-white font-bold text-sm">
                  {section.number}
                </div>
                <h2 className="text-xl font-semibold text-white">
                  {section.title}
                </h2>
              </div>
              <div className="flex items-center space-x-3">
                {section.sources && section.sources.length > 0 && (
                  <span className="text-xs text-gray-400 bg-gray-900 px-2 py-1 rounded">
                    {section.sources.length} sources
                  </span>
                )}
                <svg
                  className={`w-5 h-5 text-gray-400 transition-transform ${
                    isExpanded ? "rotate-180" : ""
                  }`}
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M19 9l-7 7-7-7"
                  />
                </svg>
              </div>
            </button>

            {/* Section Content */}
            {isExpanded && (
              <div className="p-6 border-t border-gray-700 bg-gray-850">
                <div className="prose prose-invert max-w-none">
                  <div className="text-gray-300 leading-relaxed">
                    {section.content ? (
                      <div 
                        className="markdown-content"
                        dangerouslySetInnerHTML={{ 
                          __html: section.content
                            .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
                            .replace(/\*(.*?)\*/g, '<em>$1</em>')
                            .replace(/^### (.*$)/gm, '<h3 class="text-lg font-semibold text-white mt-4 mb-2">$1</h3>')
                            .replace(/^## (.*$)/gm, '<h2 class="text-xl font-semibold text-white mt-6 mb-3">$1</h2>')
                            .replace(/^# (.*$)/gm, '<h1 class="text-2xl font-bold text-white mt-8 mb-4">$1</h1>')
                            .replace(/\n\n/g, '</p><p class="mb-4">')
                            .replace(/^(.+)$/gm, '<p class="mb-4">$1</p>')
                        }}
                      />
                    ) : (
                      <div className="flex items-center space-x-2 text-gray-500 italic">
                        <svg
                          className="w-4 h-4 animate-spin"
                          fill="none"
                          viewBox="0 0 24 24"
                        >
                          <circle
                            className="opacity-25"
                            cx="12"
                            cy="12"
                            r="10"
                            stroke="currentColor"
                            strokeWidth="4"
                          ></circle>
                          <path
                            className="opacity-75"
                            fill="currentColor"
                            d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                          ></path>
                        </svg>
                        <span>Generating content...</span>
                      </div>
                    )}
                  </div>
                </div>
                <style jsx>{`
                  .markdown-content h1, .markdown-content h2, .markdown-content h3 {
                    margin-top: 1.5em;
                    margin-bottom: 0.5em;
                  }
                  .markdown-content p {
                    margin-bottom: 1em;
                  }
                  .markdown-content strong {
                    font-weight: 600;
                    color: #fff;
                  }
                `}</style>

                {/* Data Sources */}
                {section.sources && section.sources.length > 0 && (
                  <div className="mt-6 pt-4 border-t border-gray-700">
                    <h4 className="text-sm font-semibold text-gray-400 mb-3">
                      Data Sources ({section.sources.length}):
                    </h4>
                    <div className="space-y-1">
                      {section.sources.map((source, idx) => (
                        <div
                          key={idx}
                          className="text-xs flex items-start space-x-2"
                        >
                          <span className="text-accent-500">•</span>
                          <a
                            href={source.url}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="text-primary-400 hover:text-primary-300 underline transition-colors"
                          >
                            {source.name}
                          </a>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            )}
          </div>
        );
      })}
    </div>
  );
}

